### ISSUE TITLE
The plugin is incompatible with gradle 2.12

### ISSUE THREAD

**Issue by chadshowalter** [eriwen/gradle-js-plugin#126]
Plugin com.eriwen.gradle.js fails with following exception after updating to gradle 2.12:

Could not create an instance of type com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet_Decorated.

Caused by: org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet_Decorated.
at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSetContainer.doCreate(DefaultJavaScriptSourceSetContainer.java:25)
at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSetContainer.doCreate(DefaultJavaScriptSourceSetContainer.java:10)
at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:57)
at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:52)
at org.gradle.api.internal.NamedDomainObjectContainerConfigureDelegate._configure(NamedDomainObjectContainerConfigureDelegate.java:39)
at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:73)
at build_2qgdrpqlkijmq2azbsvfblyvx$runclosure10.doCall(/home/mihasik/workspace-aktivo/aktivo/build.gradle:193)
at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:68)
at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:24)
at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
at com.eriwen.gradle.js.JavaScriptExtension.source(JavaScriptExtension.groovy:20)
at com.eriwen.gradle.js.JavaScriptExtension$source.call(Unknown Source)
at build_2qgdrpqlkijmq2azbsvfblyvx.run(/home/mihasik/workspace-aktivo/aktivo/build.gradle:192)
at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
... 50 more
Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.gradle.api.internal.file.DefaultSourceDirectorySet(java.lang.String, java.lang.String, org.gradle.api.internal.file.BaseDirFileResolver)
at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet.(DefaultJavaScriptSourceSet.groovy:26)
at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet_Decorated.(Unknown Source)
at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:49)
... 71 more

**Comment by uklance** [comment]
Possible solution discussed [here](https://discuss.gradle.org/t/defaultsourcedirectoryset-alternative/15193)

**Comment by mmikhulya** [comment]
can anybody publish new version of plugin?
It is not available neither here https://plugins.gradle.org/plugin/com.eriwen.gradle.js
nor here http://mvnrepository.com/artifact/com.eriwen/gradle-js-plugin

**Comment by eriwen** [comment]
@mmikhulya Should be on plugins.gradle.org now
