### ISSUE TITLE
Getting error with using jshint with gradle js plugin

### ISSUE THREAD

**Issue by karambirsingh** [eriwen/gradle-js-plugin#135]
I am using - 
com.eriwen:gradle-js-plugin: 2:12
com.eriwen:gradle-css-plugin:2.12
My Gradle version is : 2.14.1

js and css plugin is not available in mavenCentral as well as bintry. How to get updated plgin, please suggest or there is some other way around to get it build buing 2.12 js and css plugin.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test-cache-view-ui:jsHint'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.execute(AbstractTask.java:337)
        at org.gradle.api.internal.TaskInternal$execute.call(Unknown Source)
        at com.test.plugins.UIPlugin$_apply_closure6.doCall(UIPlugin.groovy:184)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: groovy.lang.MissingMethodException: No signature of method: static org.gradle.util.ConfigureUtil.configure() is applicable for argument types: (com
.test.plugins.UIPlugin$_apply_closure14$_closure46$_closure47$_closure50, com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet_Decorated, ja
va.lang.Boolean) values: [com.test.plugins.UIPlugin$_apply_closure14$_closure46$_closure47$_closure50@60cd4829, ...]
Possible solutions: configure(groovy.lang.Closure, java.lang.Object)
        at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet.configure(DefaultJavaScriptSourceSet.groovy:52)
        at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSet.configure(DefaultJavaScriptSourceSet.groovy)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:59)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:60)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:53)
        at org.gradle.api.internal.NamedDomainObjectContainerConfigureDelegate._configure(NamedDomainObjectContainerConfigureDelegate.java:40)
        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:68)
        at com.test.plugins.UIPlugin$_apply_closure14$_closure46$_closure47.doCall(UIPlugin.groovy:348)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:149)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:70)
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:25)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:104)
        at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
        at com.eriwen.gradle.js.JavaScriptExtension.source(JavaScriptExtension.groovy:20)
        at com.eriwen.gradle.js.JavaScriptExtension$source.call(Unknown Source)
        at com.test.plugins.UIPlugin$_apply_closure14$_closure46.doCall(UIPlugin.groovy:347)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:590)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:571)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 29 more

BUILD FAILED

**Comment by karambirsingh** [comment]
I was able to download both js and css plugin using below config -

maven {
    url "https://repo1.maven.org/maven2/"
}

But now it giving another issue, while building any ui project. My ui project don't have any direct dependencies on CompilerOptions i.e. closure-compiler.xxxxx.jar

Caused by: java.lang.NoClassDefFoundError: com/google/javascript/jscomp/CompilerOptions
        at com.eriwen.gradle.js.JsPlugin.apply(JsPlugin.groovy:38)
        at com.eriwen.gradle.js.JsPlugin.apply(JsPlugin.groovy)

**Comment by eriwen** [comment]
These NoClassDefFoundErrors are very unexpected. I'm afraid I can't reproduce the problem without a code sample. Would you please explain how you're using the plugins?

**Comment by karambirsingh** [comment]
I resolved this problem by putting required JARs on classpath like below - 

buildscript {
dependencies {
   . . . 
   classpath (group: "com.google.javascript", name: 'closure-compiler', version: closureCompilerVersion)
   classpath (group: "com.yahoo.platform.yui", name: 'yuicompressor', version: yuicompressorVersion)
}}

**Comment by neodevelop** [comment]
For the record!
Be careful using _sdkman_, when grails is calling gradle you must be sure that you're calling gradle 3.0+ and if you're using the _defaults_ in sdkman maybe cause the title error.

Regards

**Comment by eriwen** [comment]
I suspect that upgrading to `gradle-js-plugin` v2.14.1 should resolve the issue. If not, please let me know.
