### ISSUE TITLE
combinejs broken with gradle 3.4.1 and later

### ISSUE THREAD

**Issue by kaopitz** [eriwen/gradle-js-plugin#149]
I have a standard configuration as shown in the tutorial (using gradle-js-plugin 2.14.1)
javascript.source {
	dev {
		js {
			srcDir jsSrcDir
			include "*.js"
			exclude "*.min.js"
		}
	}
	prod {
		js {
			srcDir jsSrcDir
			include "*.min.js"
		}
	}
}

// Specify a collection of files to be combined, then minified and finally GZip compressed.
task combinejs(type: com.eriwen.gradle.js.tasks.CombineJsTask) {
	if (env == 'prod') {
		source = javascript.source.prod.js.files
	} else {
		source = javascript.source.dev.js.files
	}
	dest = file("${buildDir}/all.js")
}

Works perfectly fine with gradle 3.3. With gradle 3.4.1 or 3.5 it runs into an exception.

:myproject:combineJs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
path may not be null or empty string. path='null'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.IllegalArgumentException: path may not be null or empty string. path='null'
        at org.gradle.api.internal.file.BaseDirFileResolver.doResolve(BaseDirFileResolver.java:72)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:79)
        at org.gradle.api.internal.file.AbstractFileResolver.resolve(AbstractFileResolver.java:61)
        at org.gradle.api.internal.file.DefaultFileOperations.file(DefaultFileOperations.java:76)
        at org.gradle.api.internal.project.DefaultProject.file(DefaultProject.java:738)
        at org.gradle.api.Project$file$5.call(Unknown Source)
        at org.gradle.api.Project$file$5.call(Unknown Source)
        at com.eriwen.gradle.js.tasks.CombineJsTask.getDest(CombineJsTask.groovy:29)
        at com.eriwen.gradle.js.tasks.CombineJsTask_Decorated.getDest(Unknown Source)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo$4.create(TaskPropertyInfo.java:99)
        at org.gradle.util.SingleMessageLogger.whileDisabled(SingleMessageLogger.java:217)
        at org.gradle.api.internal.project.taskfactory.TaskPropertyInfo.getValue(TaskPropertyInfo.java:97)
        at org.gradle.api.internal.project.taskfactory.TaskClassValidator$FutureValue.call(TaskClassValidator.java:62)
        at org.gradle.util.GUtil.uncheckedCall(GUtil.java:402)

**Comment by kaopitz** [comment]
Sorry, issue only seemed to exist when upgrading from 3.3. to 3.4.1. After cleaning all caches, combinejs & minifyjs worked fine.
