### ISSUE TITLE
How to handle deprecated message related to Gradle 6.0 and the gradle-js-plugin ?

### ISSUE THREAD

**Issue by erajkovic** [eriwen/gradle-js-plugin#168]
With the latest version of Gradle - currently using 5.1 - I am getting a new deprecated code notice in my build:
**Internal API constructor FactoryNamedDomainObjectContaineronstructor AbstractNamedDomainObjectContainer(Class<T>, Instantiator) has been deprecated.**
When using the --stacktrace option, I am getting the following extra information:
Internal API constructor FactoryNamedDomainObjectContaineronstructor AbstractNamedDomainObjectContainer(Class<T>, Instantiator) has been deprecated. This is scheduled to be removed in Gradle 6.0. Don't use internal API
        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.<init>(AbstractNamedDomainObjectContainer.java:65)
        at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSetContainer.<init>(DefaultJavaScriptSourceSetContainer.java:17)
        at com.eriwen.gradle.js.source.internal.DefaultJavaScriptSourceSetContainer_Decorated.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.eriwen.gradle.js.JavaScriptExtension.<init>(JavaScriptExtension.groovy:16)
        at com.eriwen.gradle.js.JavaScriptExtension_Decorated.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.plugins.DefaultConvention.instantiate(DefaultConvention.java:242)
        at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:142)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.eriwen.gradle.js.JsPlugin.apply(JsPlugin.groovy:43)
        at com.eriwen.gradle.js.JsPlugin.apply(JsPlugin.groovy)
...
I am going to try to push a build scan to gradle's site (https://scans.gradle.com) to make it easier to review.

**Comment by erajkovic** [comment]
Full report should be available from https://gradle.com/s/5opyqj6szezyi - not sure if the link can be shared here - alternate URL: https://scans.gradle.com/s/5opyqj6szezyi

**Comment by 616slayer616** [comment]
I'm facing the same issue. The same goes for the [gradle-css-plugin](https://github.com/eriwen/gradle-css-plugin)

I have created PRs for both:
https://github.com/eriwen/gradle-css-plugin/pull/52
https://github.com/eriwen/gradle-js-plugin/pull/171

Maybe this helps. I hope it gets seen by a contributor.

**Comment by lorenzopolidori** [comment]
+1 Is this project still maintained?

**Comment by TeodoroFilippini** [comment]
+1, this would be great to fix

**Comment by stefanneuhaus** [comment]
Now as Gradle 6 has been released the title should state something like "Incompatibility with Gradle 6".

**Comment by lorenzopolidori** [comment]
I solved this issue switching to webpack and calling it in a custom gradle task:
```groovy
task webpackBuild(type: Exec) {
    workingDir 'base/path'
    commandLine 'npm', 'run', 'build'
}
```
