### ISSUE TITLE
NoSuchFieldError: JAVA_UPPER_CASE

### ISSUE THREAD

**Issue by ndtreviv** [eriwen/gradle-js-plugin#170]
Task :minifyJs recently stopped working.

**Plugin Version**: `id "com.eriwen.gradle.js" version "2.14.1"`

```
$ ./gradlew --version
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Mac OS X 10.14.3 x86_64
```

**Root Error**:
```
Caused by: java.lang.NoSuchFieldError: JAVA_UPPER_CASE
        at com.google.javascript.jscomp.parsing.JsDocInfoParser.validTemplateTypeName(JsDocInfoParser.java:1208)
```

**Build Stack Trace**:
```
...
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':minifyJs'.
> JAVA_UPPER_CASE

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':minifyJs'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NoSuchFieldError: JAVA_UPPER_CASE
        at com.google.javascript.jscomp.parsing.JsDocInfoParser.validTemplateTypeName(JsDocInfoParser.java:1208)
        at com.google.javascript.jscomp.parsing.JsDocInfoParser.parseAnnotation(JsDocInfoParser.java:938)
        at com.google.javascript.jscomp.parsing.JsDocInfoParser.parseHelperLoop(JsDocInfoParser.java:282)
        at com.google.javascript.jscomp.parsing.JsDocInfoParser.parse(JsDocInfoParser.java:272)
        at com.google.javascript.jscomp.parsing.IRFactory.createJsDocInfoParser(IRFactory.java:889)
        at com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:656)
        at com.google.javascript.jscomp.parsing.IRFactory.handleJsDoc(IRFactory.java:670)
        at com.google.javascript.jscomp.parsing.IRFactory.transform(IRFactory.java:733)
        at com.google.javascript.jscomp.parsing.IRFactory.access$300(IRFactory.java:163)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.processAstRoot(IRFactory.java:1013)
        at com.google.javascript.jscomp.parsing.IRFactory$TransformDispatcher.process(IRFactory.java:2591)
        at com.google.javascript.jscomp.parsing.IRFactory.justTransform(IRFactory.java:931)
        at com.google.javascript.jscomp.parsing.IRFactory.transformTree(IRFactory.java:339)
        at com.google.javascript.jscomp.parsing.ParserRunner.parse(ParserRunner.java:117)
        at com.google.javascript.jscomp.JsAst.parse(JsAst.java:89)
        at com.google.javascript.jscomp.JsAst.getAstRoot(JsAst.java:50)
        at com.google.javascript.jscomp.CompilerInput.getAstRoot(CompilerInput.java:113)
        at com.google.javascript.jscomp.Compiler.parseInputs(Compiler.java:1305)
        at com.google.javascript.jscomp.Compiler.parse(Compiler.java:713)
        at com.google.javascript.jscomp.Compiler.compileInternal(Compiler.java:674)
        at com.google.javascript.jscomp.Compiler.access$000(Compiler.java:83)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:645)
        at com.google.javascript.jscomp.Compiler$2.call(Compiler.java:642)
        at com.google.javascript.jscomp.CompilerExecutor$2.call(CompilerExecutor.java:93)
```

**Comment by oyvindhorneland** [comment]
I've also encountered this. In my case I'm also using build-info-extractor-gradle and I found that minfyJs works if I'm using build-info-extractor-gradle 4.9.0, but fails with 4.9.1+. Diff between build-info-extractor-gradle 4.9.0 and 4.9.1 (https://github.com/jfrog/build-info/commit/661a208a05fc6b0358717efa2f4c56e647b6fd9b#diff-c197962302397baf3a4cc36463dce5ea) shows that Guava has been upgraded and JAVA_UPPER_CASE was removed in https://github.com/google/guava/commit/f1249c4f0449260ff123e8da6b921a37fc058147#diff-bb82a7aa349f7e24d96641a41e92757d.

**Comment by PaulJamesMoran** [comment]
I have just upgraded AndroidStudio and hit the same problem. It now seems to require the use of the 4.10.1 gradle distribution.

Is there a work-around for this?
Eric, do you have a timeframe for when you may be able to look at this?
Paul

**Comment by raskolnikov** [comment]
I am having same issue. Is there any work around for this ? Thanks

**Comment by pavloPL** [comment]
Any progress? Does anyone has workaround? I am stuck at the moment.

**Comment by ubivent-seuffert** [comment]
we managed to republish the plugin with updated closure dependencies
plugins {
  id "eu.butter.gradle.js" version "2.15.1"
}

**Comment by slominskir** [comment]
Has eriwen abandoned this project?  It hasn't been updated in years.

**Comment by seuffert** [comment]
Sadly it looks like it...

**Comment by ndtreviv** [comment]
Time for someone to make a good fork?

**Comment by ubivent-seuffert** [comment]
the mentioned fork solves at least the problem at hand
https://github.com/tbutter/gradle-js-plugin/

**Comment by mattburns** [comment]
> the mentioned fork solves at least the problem at hand
> https://github.com/tbutter/gradle-js-plugin/

Thanks! Fixed for me

**Comment by mattburns** [comment]
Actually, that fork works until you want to use Gradle 6.0... 😭
![image](https://user-images.githubusercontent.com/1316126/93313264-29036c00-f800-11ea-88df-b73d743b3660.png)

**Comment by ubivent-seuffert** [comment]
> Actually, that fork works until you want to use Gradle 6.0... 

yes you are right, Gradle 6 is not (yet) supported in our branch. I will let you know if we find the time to commit some changes
