### ISSUE TITLE
JSDoc invocation throws exception

### ISSUE THREAD

**Issue by danielyule** [eriwen/gradle-js-plugin#68]
I have been trying to use this plugin to generate JSDoc, and have been having some difficulties

At first, I followed the example in the readme, writing

```
jsdoc {
    source = javascript.source.dev.js.files
    destinationDir = file("${buildDir}/jsdoc")
}
```

But this complained that I was defining dynamic properties for both source and destinationDir, which was deprecated.

So, I made a more explicit task like so:

```
task docs (type: com.eriwen.gradle.js.tasks.JsDocTask){
    source = javascript.source.dev.js.files
    destinationDir = file("${buildDir}/jsdoc")
}
```

This installed Rhino, but gives me the following output:

```
    [unzip] Expanding: C:\Users\Daniel\Development\glossary-dev\extension-shared\build\tmp\js\jsdoc.zip into C:\Users\Daniel\Development\glossary-dev\extension-shared\build\tmp\js\jsdoc
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\Daniel\Development\glossary-dev\extension-shared\build\tmp\js\jsdoc\jsdoc\jsdoc.js
        at java.net.URI.create(URI.java:859)
        at java.net.URI.resolve(URI.java:1043)
        at org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider.loadFromPathList(UrlModuleSourceProvider.java:112)
        at org.mozilla.javascript.commonjs.module.provider.UrlModuleSourceProvider.loadFromPrivilegedLocations(UrlModuleSourceProvider.java:93)
        at org.mozilla.javascript.commonjs.module.provider.ModuleSourceProviderBase.loadSource(ModuleSourceProviderBase.java:41)
        at org.mozilla.javascript.commonjs.module.provider.CachingModuleScriptProviderBase.getModuleScript(CachingModuleScriptProviderBase.java:69)
        at org.mozilla.javascript.commonjs.module.provider.SoftCachingModuleScriptProvider.getModuleScript(SoftCachingModuleScriptProvider.java:67)
        at org.mozilla.javascript.commonjs.module.Require.requireMain(Require.java:128)
        at org.mozilla.javascript.tools.shell.Main.processSource(Main.java:533)
        at org.mozilla.javascript.tools.shell.Main.processFiles(Main.java:178)
        at org.mozilla.javascript.tools.shell.Main$IProxy.run(Main.java:102)
        at org.mozilla.javascript.Context.call(Context.java:489)
        at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
        at org.mozilla.javascript.tools.shell.Main.exec(Main.java:160)
        at org.mozilla.javascript.tools.shell.Main.main(Main.java:138)
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\Daniel\Development\glossary-dev\extension-shared\build\tmp\js\jsdoc\jsdoc\jsdoc.js
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parse(URI.java:3039)
        at java.net.URI.<init>(URI.java:595)
        at java.net.URI.create(URI.java:857)
        ... 14 more
:docs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs'.
> Process 'command 'C:\Program Files\Java\jdk1.7.0_21\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

The problem is not with my files, as I can run JSDoc on them independent of this plugin.

I haven't the skill with Groovy or Gradle to try and debug precisely what's going on, but either the documentation or the code has a problem.  If you need more information, I am happy to provide it.

**Comment by eriwen** [comment]
It'd be cool if someone could verify this working after upgrading to JSDoc 3.3

**Comment by Jinshichi** [comment]
I've got the following error with JSDoc 3.3.3 when I'm using docstrap as the template:
`java.lang.Exception: Error: fs.readFile[Sync] requires an encoding on Rhino!`

I found a workaround for this error:

Edit docstrap/template/publish.js as follows:

before:
```
function generateQuickTextSearch(templatePath, searchableDocuments, navOptions) {
    ---
    var tmplString = fs.readFileSync(templatePath + "/quicksearch.tmpl").toString(),
          tmpl = _.template(tmplString);
    ---
}
```

after:
<pre>
function generateQuickTextSearch(templatePath, searchableDocuments, navOptions) {
    ---
    var tmplString = fs.readFileSync(templatePath + "/quicksearch.tmpl", <b>'utf8'</b>).toString(),
          tmpl = _.template(tmplString);
    ---
}
</pre>

Since NodeJS doesn't require encoding param for fs.readFileSync, common docstrap users might not aware this error. So I've not filed this issue on docstrap.

Do you have a plan to upgrade to JSDoc > 3.4?
